name: Build palera1n

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
        - 'src/**'
        - 'docs/**'
        - 'patches/**'
        - 'include/**'
        - 'Makefile'
        - 'CMakeLists.txt'
        - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (packages)
        run: |
          sudo apt-get -y update
          sudo apt-get -y install mandoc make

      - name: Build Documentation
        run: |
          make -j$(nproc) docs
          mkdir -p ready/docs
          cp docs/*.html docs/mandoc.css docs/palera1n.1 ready/docs

  build-Linux:
    strategy:
      matrix:
        triple:
        - x86_64-linux-musl
    runs-on: ubuntu-latest
    env:
      MBEDTLS_VERSION: 3.5.2
      LIBUSB_VERSION: 1.0.26
      READLINE_VERSION: 8.2
      SLANG_VERSION: 2.3.3
      NEWT_VERSION: 0.52.23
      GPM_VERSION: 1.20.7
      POPT_VERSION: 1.19

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build dependencies (packages)
        run: |
          sudo apt-get remove -y libssl-dev libreadline-dev
          sudo apt-get install -y pkg-config autoconf automake autopoint mandoc
          sudo pip3 install jsonschema jinja2

      - name: Download toolchain checksum
        run: |
          curl -LO https://musl.cc/SHA512SUMS
          echo "TOOLCHAIN_CHECKSUM="$(grep ${{ matrix.triple }}-cross.tgz SHA512SUMS | cut -d' ' -f1) >> $GITHUB_ENV

      - name: Download toolchain (cached)
        id: toolchain_cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.triple }}-cross.tgz
          key: ${{ matrix.triple }}-${{ env.TOOLCHAIN_CHECKSUM }}-toolchain

      - name: Download toolchain
        if: steps.toolchain_cache.outputs.cache-hit != 'true'
        run: |
          curl -LO https://musl.cc/${{ matrix.triple }}-cross.tgz

      - name: Setup environment
        run: |
          tar -xf ${{ matrix.triple }}-cross.tgz
          mkdir sysroot
          echo "$(pwd)/${{ matrix.triple }}-cross/bin" >> $GITHUB_PATH
          case ${{ matrix.triple }} in
            i486-linux-musl)
              echo "CHECKRA1N_NAME=linux-x86" >> $GITHUB_ENV
              echo "ARCH_NAME=i386" >> $GITHUB_ENV
              ;;
            x86_64-linux-musl)
              echo "CHECKRA1N_NAME=linux-x86_64" >> $GITHUB_ENV
              echo "ARCH_NAME=amd64" >> $GITHUB_ENV
              ;;
            armel-linux-musleabi)
              echo "CHECKRA1N_NAME=linux-armel" >> $GITHUB_ENV
              echo "ARCH_NAME=armel" >> $GITHUB_ENV
              ;;
            aarch64-linux-musl)
              echo "CHECKRA1N_NAME=linux-arm64" >> $GITHUB_ENV
              echo "ARCH_NAME=arm64" >> $GITHUB_ENV
              ;;
          esac
          echo "PKG_CONFIG_PATH=$(pwd)/sysroot/usr/local/lib/pkgconfig" >> $GITHUB_ENV
          echo "CFLAGS=-g -fdata-sections -ffunction-sections -I$(pwd)/sysroot/usr/local/include -L$(pwd)/sysroot/usr/local/lib" >> $GITHUB_ENV
          echo "CXXFLAGS=-g -fdata-sections -ffunction-sections -I$(pwd)/sysroot/usr/local/include -L$(pwd)/sysroot/usr/local/lib" >> $GITHUB_ENV
          echo "LDFLAGS=-g -Wl,--gc-sections -fdata-sections -ffunction-sections -I$(pwd)/sysroot/usr/local/include -L$(pwd)/sysroot/usr/local/lib" >> $GITHUB_ENV
          echo "INSTALL=$(command -v install) --strip-program=${{ matrix.triple }}-strip" >> $GITHUB_ENV
          echo "DESTDIR=$(pwd)/sysroot" >> $GITHUB_ENV
          echo "PREFIX=/usr/local" >> $GITHUB_ENV
          echo "CONFIGURE_ARGS=--build=x86_64-linux-gnu --host=${{ matrix.triple }} --prefix=/usr/local --disable-shared --enable-static" >> $GITHUB_ENV
          echo "CROSS_COMPILE=${{ matrix.triple }}-" >> $GITHUB_ENV
          mkdir -p $(pwd)/sysroot/usr/local/lib
          ln -sf $(pwd)/sysroot/usr/local/lib{,64}

      - name: Download dependencies (source code)
        run: |
          curl -LOOOOOOO \
            https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v${{ env.MBEDTLS_VERSION }}.tar.gz \
            https://github.com/libusb/libusb/releases/download/v${{ env.LIBUSB_VERSION }}/libusb-${{ env.LIBUSB_VERSION }}.tar.bz2 \
            https://mirror-hk.koddos.net/gnu/readline/readline-${{ env.READLINE_VERSION }}.tar.gz \
            https://www.jedsoft.org/releases/slang/slang-${{ env.SLANG_VERSION }}.tar.bz2 \
            https://releases.pagure.org/newt/newt-${{ env.NEWT_VERSION }}.tar.gz \
            https://github.com/telmich/gpm/archive/refs/tags/${{ env.GPM_VERSION }}.tar.gz \
            https://github.com/rpm-software-management/popt/archive/refs/tags/popt-${{ env.POPT_VERSION }}-release.tar.gz

          tar -xf v${{ env.MBEDTLS_VERSION }}.tar.gz
          tar -xjf libusb-${{ env.LIBUSB_VERSION }}.tar.bz2
          tar -xf readline-${{ env.READLINE_VERSION }}.tar.gz
          tar -xjf slang-${{ env.SLANG_VERSION }}.tar.bz2
          tar -xf newt-${{ env.NEWT_VERSION }}.tar.gz
          tar -xf ${{ env.GPM_VERSION }}.tar.gz
          tar -xf popt-${{ env.POPT_VERSION }}-release.tar.gz
          git clone --depth=1 https://github.com/libimobiledevice/libplist
          git clone --depth=1 https://github.com/libimobiledevice/libimobiledevice-glue
          git clone --depth=1 https://github.com/libimobiledevice/libirecovery
          git clone --depth=1 https://github.com/libimobiledevice/libusbmuxd
          git clone --depth=1 https://github.com/libimobiledevice/libimobiledevice
          git clone --depth=1 https://github.com/libimobiledevice/usbmuxd

      - name: Build Mbed TLS
        run: |
          cd mbedtls-${{ env.MBEDTLS_VERSION }}
          cat ../patches/mbedtls/0001-Allow-empty-x509-cert-issuer.patch | patch -sN -d . -p1
          mkdir build
          if [ "${{ matrix.triple }}" = "i486-linux-musl" ]; then sed -i '/define MBEDTLS_AESNI_C/d' include/mbedtls/mbedtls_config.h; fi
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CROSSCOMPILING=true \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=$(echo ${{ matrix.triple }} | cut -d- -f1) \
            -DCMAKE_C_COMPILER='${{ env.CROSS_COMPILE }}gcc' \
            -DCMAKE_C_FLAGS='${{ env.CFLAGS }}'  \
            -DCMAKE_CXX_FLAGS='${{ env.CXXFLAGS }}' \
            -DCMAKE_FIND_ROOT_PATH="${{ env.DESTDIR }}" \
            -DCMAKE_INSTALL_PREFIX="${{ env.PREFIX }}" \
            -DENABLE_TESTING=OFF \
            -DENABLE_PROGRAMS=OFF \
            -DCMAKE_INSTALL_SYSCONFDIR="/etc"
          make -j$(nproc)
          make -j$(nproc) install DESTDIR=${{ env.DESTDIR }}
          cd ..

      - name: Build libusb
        run: |
          cd libusb-${{ env.LIBUSB_VERSION }}
          ./configure ${{ env.CONFIGURE_ARGS }} --disable-udev
          make -j$(nproc)
          make -j$(nproc) install DESTDIR=${{ env.DESTDIR }}
          cd ..

      - name: Build readline
        run: |
          cd readline-${{ env.READLINE_VERSION }}
          ./configure ${{ env.CONFIGURE_ARGS }}
          make -j$(nproc)
          make -j$(nproc) install DESTDIR=${{ env.DESTDIR }}
          cd ..

      - name: Build S-Lang
        run: |
          cd slang-${{ env.SLANG_VERSION }}
          ./configure \
            ${{ env.CONFIGURE_ARGS }} \
            --without-x \
            --without-pcre \
            --without-onig \
            --without-z \
            --without-png \
            --without-iconv
          gmake -j$(sysctl -n hw.ncpu) static
          gmake -j$(sysctl -n hw.ncpu) install-static DESTDIR=${{ env.DESTDIR }}
          cd ..

      - name: Build GPM
        run: |
          cd gpm-${{ env.GPM_VERSION }}
          cat ../patches/gpm/*.patch | patch -sN -d . -p1
          ./autogen.sh
          ./configure \
            ${{ env.CONFIGURE_ARGS }}
          gmake -j$(sysctl -n hw.ncpu)
          gmake -j$(sysctl -n hw.ncpu) install DESTDIR=${{ env.DESTDIR }}
          cd ..

      - name: Build popt
        run: |
          cd popt-popt-${{ env.POPT_VERSION }}-release
          autoreconf -fiv
          ./configure \
            ${{ env.CONFIGURE_ARGS }} \
            --without-libiconv-prefix \
            --without-libintl-prefix \
            --disable-nls \
            --disable-werror
          gmake -j$(sysctl -n hw.ncpu)
          gmake -j$(sysctl -n hw.ncpu) install DESTDIR=${{ env.DESTDIR }}
          cd ..

      - name: Build newt
        run: |
          cd newt-${{ env.NEWT_VERSION }}
          ./configure \
            ${{ env.CONFIGURE_ARGS }} \
            --with-readline=gnu \
            --without-python \
            --without-tcl \
            --disable-nls \
            --with-gpm-support
          gmake -j$(sysctl -n hw.ncpu) libnewt.a
          mkdir -p ${{ env.DESTDIR }}/usr/local/{lib/pkgconfig,include}
          install -m644 libnewt.pc ${{ env.DESTDIR }}/usr/local/lib/pkgconfig
          install -m644 libnewt.a ${{ env.DESTDIR }}/usr/local/lib
          install -m644 newt.h ${{ env.DESTDIR }}/usr/local/include
          cd ..

      - name: Build libplist
        run: |
          cd libplist
          autoreconf -fiv
          ./configure ${{ env.CONFIGURE_ARGS }} --without-cython
          make -j$(nproc)
          make -j$(nproc) install DESTDIR=${{ env.DESTDIR }}
          cd ..

      - name: Build libimobiledevice-glue
        run: |
          cd libimobiledevice-glue
          autoreconf -fiv
          ./configure ${{ env.CONFIGURE_ARGS }}
          make -j$(nproc)
          make -j$(nproc) install DESTDIR=${{ env.DESTDIR }}
          cd ..

      - name: Build libirecovery (sorta)
        run: |
          sudo mv /usr/local /usr/local.bak
          sudo ln -s ${{ env.DESTDIR }}${{ env.PREFIX }} /usr/local
          cd libirecovery
          autoreconf -fiv
          ./configure ${{ env.CONFIGURE_ARGS }}
          echo -e 'all:\ninstall:' > tools/Makefile
          make -ij$(nproc)
          make -ij$(nproc) install DESTDIR=${{ env.DESTDIR }}
          install -m644 src/.libs/libirecovery-1.0.a ${{ env.DESTDIR }}${{ env.PREFIX }}/lib
          cd ..

      - name: Build libusbmuxd
        run: |
          cd libusbmuxd
          autoreconf -fiv
          ./configure ${{ env.CONFIGURE_ARGS }}
          make -j$(nproc)
          make -j$(nproc) install DESTDIR=${{ env.DESTDIR }}
          cd ..

      - name: Build libimobiledevice
        run: |
          cd libimobiledevice
          autoreconf -fiv
          ./configure ${{ env.CONFIGURE_ARGS }} --with-mbedtls --enable-debug
          echo -e 'all:\ninstall:' > tools/Makefile
          make -j$(nproc)
          make -j$(nproc) install DESTDIR=${{ env.DESTDIR }}
          cd ..
          sudo rm /usr/local
          sudo mv /usr/local.bak /usr/local

      - name: Build usbmuxd
        run: |
          cd usbmuxd
          autoreconf -fiv
          ./configure ${{ env.CONFIGURE_ARGS }} --without-systemd
          ${{ matrix.triple }}-gcc ${{ env.CFLAGS }} -I${{ env.DESTDIR }}/${{ env.PREFIX }}/include/libusb-1.0 src/*.c \
            -DHAVE_CONFIG_H -no-pie \
            -I. -static ${{ env.LDFLAGS }}} -limobiledevice-1.0 -lusbmuxd-2.0 -limobiledevice-glue-1.0  \
            -lplist-2.0 -lusb-1.0 -lmbedtls -lmbedcrypto -lmbedx509 -lpthread -o usbmuxd
          mkdir -p ${{ env.DESTDIR }}/${{ env.PREFIX }}/sbin
          ${{ matrix.triple }}-objcopy --only-keep-debug usbmuxd usbmuxd.debug
          ${{ matrix.triple }}-strip --strip-debug --strip-unneeded usbmuxd
          ${{ matrix.triple }}-objcopy --add-gnu-debuglink=usbmuxd.debug usbmuxd
          install -m755 usbmuxd usbmuxd.debug ${{ env.DESTDIR }}/${{ env.PREFIX }}/sbin
          cd ..

      - name: Build palera1n
        run: |
          cp -a ${{ env.DESTDIR }}/${{ env.PREFIX }}/{include,lib} dep_root
          find dep_root -name '*.so' -delete
          find dep_root -name '*.la' -delete
          CC="${{ matrix.triple }}-gcc" make -j$(nproc)
          cp src/palera1n palera1n.release

      - uses: actions/upload-artifact@v4
        with:
          name: testytest1
          path: src/palera1n

      - name: Seperate debug symbols
        run: |
          ${{ matrix.triple }}-objcopy --only-keep-debug palera1n.release palera1n.debug
          ${{ matrix.triple }}-strip --strip-debug --strip-unneeded palera1n.release
          ${{ matrix.triple }}-objcopy --add-gnu-debuglink=palera1n.debug palera1n.release
          chmod -x palera1n.debug
      

      - name: Prepare artifact
        run: |
          mkdir -p ready/{binaries,debian,binaries_development,build_depends,debug_symbols} usbmuxd-static
          mv palera1n.debug ready/debug_symbols/palera1n-${{ env.CHECKRA1N_NAME }}.debug
          mv palera1n.release ready/binaries/palera1n-${{ env.CHECKRA1N_NAME }}
          tar -zcf ready/build_depends/dep_root_${{ matrix.triple }}.tgz dep_root
          install -m755 sysroot/${{ env.PREFIX }}/sbin/usbmuxd usbmuxd-static/usbmuxd-${{ env.CHECKRA1N_NAME }}
          install -m755 sysroot/${{ env.PREFIX }}/sbin/usbmuxd.debug usbmuxd-static/usbmuxd-${{ env.CHECKRA1N_NAME }}.debug

      - name: Build debs
        run: |
          version="6.9.0"

          make -j$(nproc) docs
          mkdir -p stage/DEBIAN
          mkdir -p stage/usr/bin
          mkdir -p stage/usr/share/man/man1
          cp packaging/control stage/DEBIAN/control

          sed 's|@DEB_ARCH@|${{ env.ARCH_NAME }}|g' -i stage/DEBIAN/control
          sed "s|@DEB_VERSION@|$version|g" -i stage/DEBIAN/control
          
          install -Dm644 ready/binaries/palera1n-${{ env.CHECKRA1N_NAME }} stage/usr/bin/palera1n
          gzip -c9 docs/palera1n.1 > stage/usr/share/man/man1/palera1n.1.gz
          chmod 755 stage/usr/bin/palera1n
          chmod 644 stage/usr/share/man/man1/palera1n.1.gz

          dpkg-deb --root-owner-group -b stage palera1n_${{ env.ARCH_NAME }}.deb
          mv palera1n*.deb ready/debian
          rm -rf stage

      - uses: actions/upload-artifact@v4
        with:
          name: testytest
          path: ready/
